# Database
spring.datasource.url=jdbc:postgresql://db.pwyquywopuhpwspzxbgh.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.data-source-properties.sslmode=require