spring.application.name=nl-sql-engine
# Ollama
spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.model=mistral
spring.ai.ollama.chat.model=${OLLAMA_CHAT_MODEL:phi3:mini}

# Database
#spring.datasource.url=jdbc:postgresql://localhost:5432/nlsql
#spring.datasource.username=postgres
#spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Cache
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=10m

# App
server.port=${PORT:8080}
app.llm.provider=${PRODUCTION_MODEL:groq}

#GROQ
spring.ai.openai.api-key=${GROQ_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile